baseURL = 'https://bsy1141.github.io/'
languageCode = 'en-us'
title = 'Young-dev Log'
theme = "PaperMod"

[params]
  author = "Young"
  description = "개발자 Young의 기술 블로그입니다."
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  colorScheme = "auto"
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false
   [[params.socialIcons]]
    name = "github"
    url = "https://github.com/bsy1141"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/%EC%84%9C%EC%98%81-%EB%B0%B0-a6334b235/"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:bsy1141@naver.com"

[params.homeInfoParams]
  Title = "영로그"
  Content = "모든걸 기록화해보자 이참에 개발 기록도 해보려고요^____^"

